Assets/Prefab/Human/BodyParts/01 Body - Human EarL.prefab, Assets/Prefab/Human/BodyParts/01 Body - Human EarR.prefab, Assets/Prefab/Human/Human.prefab, Assets/Scripts/Enums/BodyPartType.cs
This is the first time I've used Unity (aside from following along with crappy youtube tutorials years ago when I was a wee lad), so hopefully everything's OK!
* Adjusts head collider to be both a capsule and slimmer.
* Adds eye and ear colliders which poke out enough to be attacked. Eye
colliders should be difficult to hit, but still targetable.
* Severing either foot should drop the correct body part.
* Severing the head should drop both eyes and both ears.
* Added ears to the body part enum of course.
Fixes #97
Fixes #98
Fixes #99
Discovered the following issues:
* Severing a body part will always drop its children body parts, even
if those children have already been severed.
* Colliders remain active even when a part is severed.
* This may already be known, but some items drop through …
=> Fix severed limb issues and add eye/ear colliders

Assets/Prefab/Human/Human.prefab
Fixes (unmade) issue of clients not being able to move around on a server.
It turns out the Mirror update added a flag to NetworkAnimator and NetworkTransform, 'Client Authority', which needs to be checked on any object whose information comes from its owner not the server (which is only the player in this case).
=> Fix clients being unable to move on server

Assets/Content/Scenes/MainScene.unity, Assets/Content/Systems/Managers/RoundManager.prefab, Assets/Engine/Server/Mirror/LoginNetworkManager.cs, Assets/Engine/Server/Round/RoundManager.cs
Fixes #180, Fixes #181
Funny thing is, all the tiles were off by 0.01 (i.e. 6.01 on the x axis) _except_ the one mentioned in the issue. This fixes the Main Scene. I checked the Tile system to make sure tiles created with the tool had proper rounded-off transform.positions, and they do. Maybe the tiles in the scene were created with an earlier version?
Fixes the Round timer bug and makes a few other changes to RoundManager, including a proper namespace within SS3D.Engine.
=> Fix tile transforms and round timer

Assets/Art/Models/Items/Functional/Containers/Fluid.meta, Assets/Content/Items/Functional/Containers/Fluid.meta, Assets/Content/Scenes/MainScene.unity, Assets/Content/Structures/Fixtures/Doors/DoorOpener.cs, Assets/Content/Structures/Fixtures/Doors/airlock.prefab, Assets/Content/Structures/Walls/Assemblies.meta, Assets/Content/Systems/Tiles.meta, Assets/Content/Systems/Tiles/TileServerManager.cs, Assets/Content/Systems/Tiles/TileServerManager.cs.meta, Assets/Engine/Server/Mirror/LoginNetworkManager.cs, Assets/Engine/Tile/TileManager.cs
This is needed so that the sub-objects (which can only be networked SOMETIMES because mirror's fucked) have something to make requests through.
Please note that whilst this makes the code slightly uglier, it is unfortunately the only long-term stable way of doing code with Mirror (if you've done enterprise frontend/backend api systems you'll see them use the same thing).
Scene changes:
- Adds the TileServerManager component to the TileMap object. That's it.
=> Create a controller that handles all tile networking

Assets/Content/Systems/Managers/RoundManager.prefab, Assets/Engine/Utilities/DestroyOnRemote.cs, Assets/Engine/Utilities/DestroyOnRemote.cs.meta
Simply removes the "Restart Round" button for non-hosts.
The implementation is not perfect, as it simply checks if it is running on the server.
This should be changed when proper server roles are implemented.
Fixes #207
=> Hide restart button for non-hosts

Assets/Content/Creatures/Human/Human.prefab, Assets/Content/Items/Functional/Containers/Object/medkit.prefab, Assets/Content/Items/Functional/Generic/Paper Note1.prefab, Assets/Content/Items/Functional/Generic/boombox.prefab, Assets/Content/Items/Functional/Generic/pen.prefab, Assets/Content/Items/Functional/Generic/toolbox.prefab, Assets/Content/Items/Functional/Materials/glass.prefab, Assets/Content/Items/Functional/Materials/metal rod.prefab, Assets/Content/Items/Functional/Materials/metal.prefab, Assets/Content/Items/Functional/Materials/wood plank.prefab, Assets/Content/Items/Functional/Tools/Custodial/mop.prefab, Assets/Content/Items/Functional/Tools/Custodial/soap.prefab, Assets/Content/Items/Functional/Tools/Generic/Fire extinguisher.prefab, Assets/Content/Items/Functional/Tools/Generic/crowbar.prefab, Assets/Content/Items/Functional/Tools/Generic/flashlight.prefab, Assets/Content/Items/Functional/Tools/Generic/wrench.prefab, Assets/Engine/Inventory/Extensions/WearableContainer.cs, Assets/Engine/Inventory/Item.cs
Provides the ability for items to define custom offsets and rotations for wearable containers.
Most prefabs in the main scene were changed to add attachment points.
The attachment point is specified using a child object using position/rotation, then assigned to the item behaviour.
The prefab edit preview is a bit confusing, and there seems to be some wrong calculation in there.
This does not affect the in-game handling.
Resolves #229
More changes are required to handle #203, but this already makes the flashlight a bit useful.
=> Individual attachment positions

Assets/Content/Systems/Interactions/Drops.cs, Assets/Engine/Inventory/Extensions/Hands.cs, Assets/Engine/Inventory/Extensions/WearableContainer.cs, Assets/Engine/Inventory/Inventory.cs, Assets/Engine/Inventory/UI/UIInventory.cs
Placed items have the same rotation as when they were picked up.
Fixes #231
=> Ensure items get placed in same rotation as pickup

Assets/Content/Furniture/Machinery/Generic/Console - Surgery.prefab, Assets/Content/Furniture/Machinery/Generic/Display.mat, Assets/Content/Furniture/Machinery/Generic/Display.mat.meta
Makes the console's inactive screen and the display itself separate GameObjects and materials. Properly configures the display to be emissive.
It needs 2 separate video players to work properly. Later on these will need to be synced via scripts or implemented better.
Fixes #260
=> Fix console display

Assets/Art/Animations/World.meta, Assets/Art/Models/VFX.meta, Assets/Art/Models/VFX/Generic.meta, Assets/Art/Shaders/VFX.meta, Assets/Art/Shaders/World.meta, Assets/Content/World/VFX/Water.meta, Assets/Content/World/VFX/Weapons.meta
This PR removes some left-over .meta files from the recent asset retraction.
=> Remove left-over meta files from recent asset retraction

Assets/Content/Scenes/MainScene.unity, Assets/Content/World/VFX/Icon Render.prefab, Assets/Content/World/VFX/Icon Render.prefab.meta
- Adjusts the Icon Render light values to be slightly more pleasing. 
- Makes the Icon Render a prefab, and adds it to the Main Scene, so we don't have to merge MainScene if we change it in the future.
=> Make Icon Render prefab

Assets/Content/Graphics/UI/Interaction/RadialMenuUI/Classic/RadialMenuList.prefab, Assets/Engine/Interactions/UI/RadialInteractionMenuUI.cs
When there is no interaction selected, the selection wheel will not appear
Fixes #362
=> Removes interaction opacity when not selected

Assets/Engine/Interactions/InteractionHandler.cs, Assets/Engine/Interactions/UI/RadialMenuInteraction/PetalsManager.cs, Assets/Engine/Inventory/UI/UIGroupedContainers.cs, ProjectSettings/InputManager.asset
Fixes the radial menu shortcuts. Alt no longer executes the first interaction, making it possible to use the alt + right click menu. It is also possible to right click an item in hand.
Executing the first interaction on the selected item is Z.
Fixes #355
=> Fix interaction keys

Assets/Content/Creatures/Human/Human.prefab
Makes the interaction raycast ignore the player movement collider.
Fixes #352
=> Fix interaction player raycast

Assets/Content/Items/Functional/Tools/Generic/Crowbar.cs, Assets/Content/Items/Functional/Tools/Generic/Wrench.cs, Assets/Content/Items/Functional/Tools/Generic/crowbar.prefab, Assets/Content/Items/Functional/Tools/Generic/wrench.prefab, Assets/Content/Systems/Interactions/ConstructionInteraction.cs, Assets/Content/Systems/Interactions/ConstructionInteraction.cs.meta, Assets/Content/Systems/Interactions/TableConstructionInteraction.cs, Assets/Content/Systems/Interactions/WallConstructionInteraction.cs
Prevents the player from building on a tile a player is on.
Can also be used to check for other layers.
Adds a new abstract class ConstructionInteraction for constructions, which implements the obstacle check.
Fixes #366
=> Add obstacle support to construction

Assets/Engine/Tile/Connections/AdvancedAdjacencyConnector.cs, Assets/Engine/Tile/Connections/TieredAdvancedAdjacencyConnector.cs
I don't know why but, the connections got messed up on the advanced scripts at some point (all connection scripts based of the simple script shouldn't be affected by this).
This fixes the X connection errors on tables, walls, windows.
BEFORE
AFTER
T & L connections still seem to be messed up, but only on the TieredAdvancedAdjacencyConnector (used on windows), but I'm not sure why, as comparing them to the AdvancedAdjacencyConnector, they seem fine. So I'm not sure why T& L are broken for windows still... I even checked the .fbx and didn't see anything out of place.
=> Fix X connections on advanced scripts

.github/workflows/main.yml
Updates the upload artifact to version 2.
This fixes a bug in the original upload artifact, where the action runs on the host VM even when a container is specified.
This leads to missing files because the docker container is not mapped to the same location on the host.
See actions/upload-artifact#13
=> Update to upload artifact-v2

.github/workflows/main.yml
Current unity build arguments seem to use a custom build script that is not included in the project.
This pr changes it to use arguments from the Unity documentation.
=> Modify build to use offical unity arguments

Assets/Content/Creatures/Human/Human.prefab, Assets/Content/Systems/Interactions/ToggleInteraction.cs, Assets/Engine/Interactions/Extensions/InteractionExtensions.cs, Assets/Engine/Interactions/Extensions/InteractionSourceExtension.cs, Assets/Engine/Interactions/IInteractionOriginProvider.cs, Assets/Engine/Interactions/IInteractionOriginProvider.cs.meta, Assets/Engine/Interactions/IInteractionRangeLimit.cs, Assets/Engine/Interactions/RangeLimit.cs, Assets/Engine/Interactions/RangeLimit.cs.meta, Assets/Engine/Inventory/Extensions/Hands.cs
The range code now checks horizontal and vertical distance separately, making interacting feel more consistent.
The origin of the distance check is now consistent, even when holding items.
IInteractionRangeLimit now returns a new RangeLimit struct instead of a simple float value.
IInteractionOriginProvider can be used to give an source a custom origin.
The range check origin object is now the first object in the tree with a range limit component and not the first source.
Fixes #474
Fixes #381
=> Fix inconsistent interaction range

Assets/Engine/Atmospherics/AtmosRagdoll.cs, Assets/Engine/Tile/TileManager.cs, Assets/Engine/Tile/TileObject.cs
Fixes an error where a fixture without an adjacency connector would throw an exception, aborting a chunk and causing missing tiles.
Also ensures single tile errors will never abort the rest of a chunk.
Fixes #497
=> Fix tilemap sync

Assets/Content/Structures/Walls/Wall - Metal Reinforced.asset, Assets/Content/Structures/Walls/Wall - Metal.asset, Assets/Content/Structures/Walls/Window - Metal Reinforced.asset, Assets/Content/Structures/Walls/Window - Metal Reinforced.prefab, Assets/Content/Structures/Walls/Window - Metal.asset, Assets/Content/Structures/Walls/Window - Metal.prefab
Fixes the ID names on the walls and windows. I forgot to make sure they were matching on both the .prefabs and the .assets, and this was causing some issues with the windows not connecting properly.
This changes the scene only because the scene updated with the proper asset/prefab info.
=> Fix wall & window name error

Assets/Engine/Tile/Editor/TileMap/TileMapEditor.cs
Adds a basic scrollbar to the tilemap editor. Visual help and Add Tile Type are accessible from any point in the scrolling.
=> Tilemap editor scrolling

Assets/Engine/Inventory/Inventory.cs
Removes the issue where twice the number of slots appeared for held toolboxes / medkits.
AddRange() was being used to add Containers within the Inventory.GetContainers() method. This led to the held mobile inventories being returned by both twice (once in their own right, once as a child of the player inventory). Simple check added to prevent duplicate addition into list.
Closes #514
=> Resolved doubling of Mobile Container UI

Assets/Libraries/SSRT/Shaders/Resources/SSRTLib.cginc
Flip SSRT when using OpenGL drivers, allowing it to render correctly.
Fixes #488
=> OpenGL SSRT Fix

Assets/Content/Structures/Doors/Classic Airlocks/Airlock Classic.prefab, Assets/Content/Structures/Doors/Classic Airlocks/Airlock Double Classic.prefab, Assets/Content/Structures/Doors/Station Airlocks/Airlock Glass.prefab, Assets/Content/Structures/Doors/Station Airlocks/Airlock.prefab, Assets/Content/Structures/Doors/Station Airlocks/Civilian/Airlock Civilian Glass.prefab, Assets/Content/Structures/Doors/Station Airlocks/Civilian/Airlock Civilian.prefab, Assets/Content/Structures/Doors/Station Airlocks/Double Airlock.prefab, Assets/Content/Structures/Doors/Station Airlocks/Maintenance/Airlock Maintenance Glass.prefab, Assets/Content/Structures/Doors/Station Airlocks/Maintenance/Airlock Maintenance.prefab
The interaction with airlocks was already implemented, but because the interaction system ignores Trigger colliders, they were bugged.
To fix that, I added a kinematic RigidBody to the main GameObject of the doors. When a GameObject has a RigidBody, the colliders of each child objects are interpreted as being its own, so the raycast hits work like they should.
https://user-images.githubusercontent.com/24720405/107721118-91c11880-6cba-11eb-8f18-a3893a91f665.mp4
Changed the prefab of every door.
- Basically impossible to interact with an open door because the mesh goes completly into the wall.
- Currently, clicking on a door while it's opening will trigger th open/close event again and the door will close immediately once it's fully open. This could be fixed somewhat easily by doing changes …
=> Fix interaction with airlocks

Assets/Engine/Interactions/Extensions/InteractionExtensions.cs
Attempts to enhance the interaction distance check. Also implements a check to check if the interaction point is not on the top of a wall.
Ensures that the distance test will return true if any part of the target object is close enough to the player, and not only the interaction point.
The top of doors is now interactible and you cant place items directly on top of walls.
https://user-images.githubusercontent.com/24720405/108006305-df4ec580-6fd9-11eb-8501-61dad7cc2ae9.mp4
Check distance to interaction point. If it fails, look for the point on the target's collider that is closest to the interaction source and checks the distance to there. This 
#236 can still cause items to end up on the top of walls.
Closes #614
=> Enhance interaction distance check

Assets/Engine/Interactions/Extensions/InteractionExtensions.cs
Deadzone was to big and was preventing light interactions.
Closes #535 
#610 works fine now
=> Reduce deadzone ( 0.4 -> 0.1) when checking for wall top

Assets/Content/Systems/Player/CameraFollow.cs, Assets/Engine/Interactions/Extensions/InteractionExtensions.cs
This PR changes camera rotation from Q and E keys to middle mouse
- Clicking and dragging to rotate
- Clicking, and flick-dragging to snap to a direction
- It is possible to change the minimum mouse movement speed required for snapping using _horizontalRotationFlickLimit_ field in inspector
Fixes #601
=> Change camera rotation to be done with the middle mouse (#601)

Assets/Content/Furniture/Machines/Science/Cell Charger.prefab, Assets/Engine/Inventory/AttachedContainerGenerator.cs
Basically allows Attached Containers to have a starting FIlter, something that was removed from the old system, only implemented in the Cell Charger for now, it will now correctly filter the item so only power cells can be put in it
It only adds a StartFilter variable to the AttachedContainerGenerator script since it's the most efficient way without having to to remove the readonly keyword from the Container Filters
Fixes #646
=> Adds StartFilters to Attached Containers

Packages/manifest.json
Fix Mirror namespace errors caused by outdated VSCode editor package.
You may need to regenerate your project files (Edit>Preferences>External Tools) after updating.
=> Update VSCode package

Assets/Content/Systems/Managers/LoadingScreenManager.cs, Assets/Engine/Server/Round/LoadingSceneUIHelper.cs
Fixes an issue where the map will not load after you have disconnected from the server lobby. This affected both servers and clients.
Anonymous delegates within LoadingScreenManager and LoadingSceneUIHelper were named, and unsubscribed from static mapLoaded event when the scene closes.
Although this closes the primary issue listed in #673, it does not solve the issue of the client being unable to disconnect. I will raise a separate issue for that so that #673 can be closed out.
Closes #673
=> Fixes issue where clients can't host after quitting server

Assets/Content/Systems/UI/Engine/ServerLobby/MainLobbyButtonHelper.cs
The Disconnect button previously did not work for clients either in-game or in the server lobby (i.e. once they had selected 'Join' in the main menu). It now works, and returns the client to the main menu.
I changed the way that MainLobbyButtonHelper decided whether it is the server or the client. According to the Mirror API, a client does not know its own connectionId, so I checked whether the networkConnection was unable to be assigned.
Closes #698
=> Fixes Disconnect button for clients

Assets/Content/Items/Functional/Tools/Generic/DeskLamp.cs, Assets/Content/Items/Functional/Tools/Generic/Flashlight.cs, Assets/Content/Items/Functional/Tools/Generic/desk lamp.prefab, Assets/Content/Items/Functional/Tools/Generic/flashlight.prefab
Previously flashlight and desk lamp bulb materials have been static when toggling light. This caused them to look on despite being off.
There are already 2 open PRs on this issue (but only for the flashlight). Since FlashlightInteraction.cs was deleted, these PRs can't be merged.
Thanks to jake34b and their PR for reference.
https://user-images.githubusercontent.com/26187000/121820957-e5a63300-cc95-11eb-8386-7b2dc0c9bd14.mp4
https://user-images.githubusercontent.com/26187000/121820962-efc83180-cc95-11eb-8e6d-e451cff05805.mp4
Closes #232
=> Toggle flashlight and desk lamp bulb materials

Assets/Content/Items/Functional/Containers/Object/Toolboxes/Toolbox Red.prefab, Assets/Content/Systems/UI/Game/Inventory/ContainerDisplay.prefab, Assets/Engine/Inventory/AttachedContainer.cs, Assets/Engine/Inventory/UI/ContainerUi.cs
See issue #701 . The name of the container is now displayed at the top of the containerUI.
The quality of the picture looks terrible, but that's how I see the game, I never found out why that was happening. I think it affects only me though. It should look normal on your side.
Added a text GameObject  to the containerDisplay.
Add a method GetName() to attachedContainers to get the name of the object on which the container is attached. It's done in a robust manner and in coherence with the Examine system.
Closes #701
=> add name of containers to the containerUI

Assets/Content/Structures/Doors/Door.cs, Assets/Engine/Tile/State/FixtureStateMaintainer.cs, Assets/Engine/Tile/Tile.cs
Base airlocks off of FixtureState instead of DoorState, using Rotation instead of Orientation.
- Airlocks will need to be remapped.
- Airlock prefabs may need to be updated.
These can be left to another PR to avoid merge conflicts.
Fixes #710
=> Airlock fixture rotation

Assets/Engine/Inventory/Container.cs
Closing the game by the client when somebody holds an Item in hand causes client's freezing. This PR fixes this freezing.
Assets/Engine/Inventory/Container.cs - fixed `Container.Destroy()` and `Container.Dump()` methods.
Freezing was caused by strange `while` loop in `Container.Destroy()` method (similar loop also is in `Container.Dump()`) that accidently became infinite. If I understand correctly, this part of code should destroy every `Item` in the container and after that clear item's collection.
Closes #674
=> Fix infinite loop when container is destroying or dumping

Assets/Content/Items/Clothing/Headwear/Helmets/HardHatRed.prefab, Assets/Content/Items/Clothing/Headwear/Helmets/HardHatYellow.prefab, Assets/Content/Items/Functional/Containers/Liquid/LargeBeaker.prefab, Assets/Content/Items/Functional/Containers/Liquid/SmallBeaker.prefab, Assets/Content/Items/Functional/Containers/Liquid/beaker.prefab, Assets/Content/Items/Functional/Containers/Liquid/mug.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonBlack.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonBlue.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonGreen.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonOrange.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonPurple.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonRed.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonWhite.prefab, Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonYellow.prefab, Assets/Content/Items/Functional/Parts/Power Cells/BluespacePowerCell.prefab, Assets/Content/Items/Functional/Parts/Power Cells/HighPowerCell.prefab, Assets/Content/Items/Functional/Parts/Power Cells/HyperPowerCell.prefab, Assets/Content/Items/Functional/Parts/Power Cells/PowerCell.prefab, Assets/Content/Items/Functional/Parts/Power Cells/SuperPowerCell.prefab, Assets/Engine/Inventory/Item.cs
Prefabs for all offending Items have been placed in the correct layer. Additionally, any Item that spawns on the incorrect layer will now have a warning during Awake(), so that the developer can resolve the issue.
Closes #735
=> Corrects issue where items are not on the Item layer.

Assets/Content/Entities/Humanoids/Human/HumanRagdoll.cs
When a player is knocked down (for example, by tripping over a banana peel), one of the items in their hands will be dropped. This mitigates the current issue where an item held by the player will no longer be rendered once they fall (so you can no longer see the player is holding something), but actually remains within their hands. Future changes outside the scope of this PR will see both items dropped, if they are holding two items.
There is a known bug where only one item is dropped if two are being held. That is due to an InvalidOperationException originating in Container.Dump() due to a collection being modified while iterated over. It may be fixed within the container rework.
=> Drops held item when player is knocked down.

Assets/Content/Systems/Player/HumanoidMovementController.cs
Replaces animation value being set from our internal velocity to the humanoids true velocity. An update to how the `CharacterController.Move` is called was required to ensure it was updated correctly.
https://user-images.githubusercontent.com/40436415/130316570-af7a0a14-a3d8-437f-b2db-b7e058cc6531.mp4
- [HumanoidCharacterController.cs](https://github.com/RE-SS3D/SS3D/compare/master...Liam-Harrison:humanoid-walking?expand=1#diff-2d10a69e56bbaefb1cef0eed6c9c4f401c95bd6d26fda05bf989fb37410e7755)
- `CharacterController.Move()` is designed to be called frequently, we previously only called `Move()` whenever we were moving (input vector non-zero). However this means internally the `CharacterController.velocity` is not updated frequently, and can be stuck at a low value such as `0.2`, which will …
=> Use true velocity for Humanoid animator, Fixed updating mistake

Assets/Content/Systems/Player/PlayerListener.cs
The player prefab contains an audio listener. This PR destroys the audio listener of other players, to prevent multiple audio listeners being active in multiplayer.
Minor changes to PlayerListener.cs
While testing this issue, I noticed that when clients join at the start of the round, their player is a child of MiniStation. However, late joining clients have their player as a child of the ServerLobby. This will require remediation in future work.
Closes #795
=> Prevent multiple audio listeners

Assets/Engine/Examine/Examinator.cs
Performs a check to ensure that only the local player has an Examinator (and consequently an ExamineUI). This prevents an issue in multiplayer where each player's hover text is overlaid across the default "Examine Name" hovertext.
Original issue: "Wood Floor Tile" is overlaid with "Examine Name".
=> Prevents duplicate Examinators and ExamineUIs

Assets/Content/Systems/Interactions/OpenInteraction.cs
Gets rid of the discrepancy where the player can close an open locker but viewing the contents of the locker is just beyond interaction range.
OpenInteraction.cs has had additional checks added - see Technical Notes.
Technically, the OpenInteraction (which also handles closing) and ViewContainerInteraction had exactly the same range - 1.5 units horizontally, and 1 unit vertically. However, OpenInteraction performed a single RangeCheck as part of CanInteract, whereas ViewContainerInteraction performed two. The second RangeCheck in ViewContainerInteraction is part of the Entity.CanInteract() method. The crucial difference between these RangeChecks is that the Entity.CanInteract() RangeCheck uses the distance to the target's position, and the other RangeCheck uses the interaction point …
=> Removed inconsistent ranges for opening/closing and viewing lockers.

Assets/Content/Systems/UI/Game/Chat/ChatWindow.prefab, Assets/Engine/Chat/ChatWindow.cs
This PR fixes issue #782 regarding messages sending when the window goes out of focus. It also adds the ability to send a message by pressing Enter.
* `ChatWindow.cs` has been updated a bit, I added a couple of methods.
* `ChatWindow.prefab` has also been updated. I linked new methods to the onSelect and onDeselect callbacks (?) of the text input.
* `ChatWindow` now has a `isSelected` public attribute that is true when the input field is in focus.
* `ChatWindow` has an `Update` method that checks if Enter is pressed and if the input field is in focus, and sends the message if that's the case. 
* The call to unfocus the input field after a message is sent has been moved to the end of the `SendMessage` method.  
Fixes #782
=> Fix chat message sending when out of focus

Assets/Engine/Inventory/AttachedContainerGenerator.cs, Assets/Engine/Inventory/ContainerSync.cs, Assets/Engine/Inventory/Extensions/Hands.cs
Resolved exception in ContainerSync being thrown when client joins. 
Exception was caused by TargetSyncContainer() being called on the Human prefab before the Start() function.
A subsequent issue was caused by AttachedContainer.Container not being set by the time TargetSyncContainer() was called - again, on the Human prefab. This was resolved by setting AttachedContainer.Container in Awake() instead of Start().
Exception was identified in #793, although was not the root cause of the described behaviour. Request @stilnat to confirm that exception can no longer be replicated.
=> Container System: Resolve ContainerSync OutOfRangeException on client embark

Assets/Content/Furniture/Machines/Kitchen/Microwave/microwave.prefab, Assets/Content/Furniture/Storage/Fridge/fridge.prefab, Assets/Content/Furniture/Storage/Lockers/Locker.prefab, Assets/Content/Furniture/Storage/Lockers/LockerSecure.prefab
Remove BoxCollider from several door objects inside of prefabs to prevent player from clipping into object upon interacting with the door.
Before commit; clipping issue:
https://streamable.com/clx47b
After commit; no clipping issue:
https://streamable.com/8cel8y
All had BoxColliders removed from respective door.
Assets/Content/Furniture/Machines/Kitchen/Microwave/microwave.prefab
Assets/Content/Furniture/Storage/Fridge/fridge.prefab
Assets/Content/Furniture/Storage/Lockers/Locker.prefab
Assets/Content/Furniture/Storage/Lockers/LockerSecure.prefab
As I mentioned in #816 :
>Video demonstration:
>https://streamable.com/clx47b
>
>The simplest solution to this problem would be to remove the collider for the fridge door, since that is what clips the player into the fridges mesh and doesn't …
=> Remove BoxColliders from several aesthetic doors

Assets/Art/Shaders/ItemPreview.shader, Assets/Art/Shaders/ItemPreview.shader.meta, Assets/Content/World/Palette05Emission.mat, Assets/Engine/Inventory/Item.cs, Assets/Engine/Inventory/UI/ItemDisplay.cs, Assets/Engine/Utilities/RuntimePreviewGenerator.cs
Improve the rendering for item previews in the inventory.
Add item preview shader with fake lighting.
Enable mipmaps and filtering for item previews.
Add an outline effect to item display slots.
Fix emission transparency bug.
Emission could still use some work.
Transparent items aren't supported properly yet.
The laser gun sprite has some kind of rendering issue, not caused by this PR.
=> Item rendering improvements

Assets/Content/Structures/Doors/Door.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyBitmap.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyShape.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyShape.cs.meta, Assets/Engine/Tile/TileRework/Connections/AdjacencyShapeResolver.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyShapeResolver.cs.meta, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/AdvancedAdjacency.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/OffsetAdjacency.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/SimpleAdjacency.cs, Assets/Engine/Tile/TileRework/Connections/MultiAdjacencyConnector.cs, Assets/Engine/Tile/TileRework/Editor/AdjacencyEditor.cs
* Created new AdjacencyShape enum to store possible "shapes" connectors can take
* Created AdjacencyShapeResolver, a service class meant containing all logic related to deciding which shape to use
* Refactored relevant classes to use the new service
* Minor namespace and style fixes in files that were touched
This allows for easier management of future shapes used in new types of connectors. Additionally, it makes further refactors to AdjacencyBitmap and other adjacency classes easier.
Closes #864
=> refactor adjacency shape logic into its own service

Assets/Engine/Tile/TileRework/Connections/AdjacencyBitmap.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/AdvancedAdjacency.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/OffsetAdjacency.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/SimpleAdjacency.cs, Assets/Engine/Tile/TileRework/Tile.cs
* removes Orientation (vertical/horizontal) from Tile.cs
* updates adjacency classes using Orientation for rotation calculations to use Direction instead
closes #866
=> remove outdated orientation enum

Assets/Content/Entities/Humanoids/Human/RigidBodyInspector.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyMap.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyShapeResolver.cs, Assets/SS3D.asmdef, Assets/SS3D.asmdef.meta, Assets/Tests.meta, Assets/Tests/AdjacencyShapeResolverTest.cs, Assets/Tests/AdjacencyShapeResolverTest.cs.meta, Assets/Tests/Tests.asmdef, Assets/Tests/Tests.asmdef.meta
Hopefully a start to proper automated testing within the project. Ideally once we have bigger coverage these can be run on CI with every commit and a discord message when the tests fail so we catch stuff we break early. But that's for later.
* Add unit tests for success scenarios of AdjacencyShapeResolver service
* Add assembly definition for project so test classes can access it (Ideally we would split the entire project into multiple assemblies, but at the moment its a mess and I couldnt do it quickly)
The tests require having their own assembly as per how Unity works. But this hides all other code from them, unless I reference the codes assemblies. This is a problem since our code is not split up into assemblies (but it really should be! There is no need to recompile all the files when …
=> add unit tests for AdjacencyShapeResolver

Assets/Content/Items/Functional/Tools/Construction/Crowbar.cs, Assets/Content/Items/Functional/Tools/Construction/Welders/Welder.cs, Assets/Content/Items/Functional/Tools/Construction/Wrench.cs, Assets/Content/Structures/Doors/Door.cs, Assets/Content/Systems/Construction/ConstructionMaterial.cs, Assets/Content/Systems/Construction/ItemConstructionInteraction.cs, Assets/Content/Systems/Construction/TurfConstructionInteraction.cs, Assets/Content/Systems/Interactions/ConstructionInteraction.cs, Assets/Content/Systems/Interactions/WallConstructionInteraction.cs, Assets/Engine/Examine/CompositeItemSelector.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyMap.cs, Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/AdjacencyDataStructs.cs, Assets/Engine/Tile/TileRework/Connections/IAdjacencyConnector.cs, Assets/Engine/Tile/TileRework/Connections/MultiAdjacencyConnector.cs, Assets/Engine/Tile/TileRework/Editor/AdjacencyEditor.cs, Assets/Engine/Tile/TileRework/Editor/TileDragHandler.cs, Assets/Engine/Tile/TileRework/Editor/TileMapEditor.cs, Assets/Engine/Tile/TileRework/Editor/TileObjectMigrator.cs, Assets/Engine/Tile/TileRework/PlacedTileObject.cs, Assets/Engine/Tile/TileRework/TileManager.cs, Assets/Engine/Tile/TileRework/TileMap.cs, Assets/Engine/Tile/TileRework/TileObject.cs, Assets/Engine/Tile/TileRework/TileObjectSo.cs, Assets/Engine/Tile/TileRework/TileObjectType.cs, Assets/Engine/Tile/TileRework/TileObjectType.cs.meta, Assets/Engine/Tile/TileRework/TileRestrictions.cs, Assets/Tests/AdjacencyShapeResolverTest.cs
* create enums for TileObjectGenericType and TileObjectSpecificType
* update all scriptable objects (used by tilemap editor) with their relevant enum values
* update other scripts that rely on TileObjectSo to correctly handle the new enum type
* various minor code style, naming convention and namespace updates on touched files
This has minor improvements on memory usage, but the main purpose of this was to allow for proper logic and comparisons within code for upcoming adjacency types. Strings entered by hand are error prone to typos and unreliable for logic in general. Tested map loading/saving just in case and tilemap editor with walls, tables and wires.
I got all the enum values from the scriptable objects in Assets/Content/Resources as that is what the tilemap editor uses to populate …
=> update tile object so generic and specific types to enums

.github/workflows/testrunner.yml
* Create test runner workflow
* Add discord webhook secret (done by @cosmiccoincidence)
This will execute all the edit and play mode tests within the project on every commit ~and pull request~. The results will be displayed within github actions. ~Ideally we'd have a discord bot post in the git-log channel when tests fail to make everyone aware, but that needs to be done separately from this.~ When a test execution fails, a discord message will also be displayed to let everyone know.
The discord message feature requires a new secret to be added to github, which @cosmiccoincidence has already done.
Actions executed by this workflow:
1. Clone the repository
2. Execute Edit and Play mode tests
3. Send discord message if tests fail
4. Upload test results as an artifact for reviewing
New …
=> add test runner workflow for each commit
