Assets/Materials/Palette05 Emission.mat, Assets/Materials/Palette05 Emission.mat.meta, Assets/Materials/Palette05.mat, Assets/Materials/Palette05.mat.meta
Palette05 and Palette05 Emission
=> New Materials

Assets/Models/Creatures/Robotic/AI turret.meta, Assets/Models/Furniture/Vendors.meta, Assets/Models/Items/Consumables/Food.meta, Assets/Models/Items/Consumables/Medical.meta, Assets/Models/Items/Containers.meta, Assets/Models/Items/Functional/Generic.meta, Assets/Models/Items/Materials/Construction.meta, Assets/Models/Items/Materials/Other.meta, Assets/Models/Items/Materials/Parts.meta, Assets/Models/Items/Toys.meta, Assets/Models/Items/Weapons.meta, Assets/Models/Structural/Infraestructure.meta, Assets/Prefab/Creatures/Player/Humanoid/Clothes.meta, Assets/Prefab/Creatures/Player/Humanoid/Species/Human.meta, Assets/Prefab/DefaultBody.prefab, Assets/Prefab/Furniture/Vendors.meta, Assets/Prefab/Items/Consumables/Food.meta, Assets/Prefab/Items/Consumables/Medical.meta, Assets/Prefab/Items/Functional/Generic.meta, Assets/Prefab/Items/Materials/Construction.meta, Assets/Prefab/Items/Materials/Other.meta, Assets/Prefab/Items/Materials/Parts.meta, Assets/Prefab/Items/Toys.meta, Assets/Prefab/Items/Weapons.meta, Assets/Prefab/Structural/Infrastructure.meta, Assets/Scenes/BoxStation.unity, Assets/Scenes/MainScene.unity, Assets/Scripts/HumanMovement.cs, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/InputManager.asset
The animation is based on the y position of the player, thus the
code assumes that the entire station will be flat.
Only once the player goes below a certain height it will animate
the position based on a sine wave.
=> Add space bobbing animation

Assets/Scenes/MainScene.unity, Assets/Scripts/CameraFollow.cs, ProjectSettings/InputManager.asset, ProjectSettings/ProjectSettings.asset
Some changes in camera movement and Q/E camera rotation.
=> Bit better camera

Assets/Prefab/Structural/Infrastructure/Airlocks/airlock.prefab, Assets/Prefab/Structural/Infrastructure/Airlocks/doubleairlock.prefab, Assets/Scripts/AirlockManager.cs
- Added close on timing
- TryOpen and TryClose for calling from outside of AirlockManager.
=> #40 Airlocks fix, features and refactoring

.github/ISSUE_TEMPLATE/feature-.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/user-story.md
Creating issue templates for our new kanban process
=> Creating issue templates

.github/ISSUE_TEMPLATE/feature-.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/user-story.md, Assets/Mirror/Components/NetworkTransformBase.cs, Assets/Mirror/Components/NetworkTransformWithSnapping.cs
Added Class NetworkTransformWithSnapping that allows teleport if distance passes threshold.
Edit on NetworkTransformBase to allow overriding of function
=> Network transform with snapping

.github/ISSUE_TEMPLATE/feature-.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/user-story.md
Creating issue templates for our new kanban process
=> Creating issue templates (#48)

.github/ISSUE_TEMPLATE/feature-.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/user-story.md
Creating issue templated for our new kanban process
=> Creating issue templates (#48) into develop

CONTRIBUTING.md
=> Update model list link

Assets/Scripts/Structure/Door.cs
Fixes un-created issue about airlocks creating wallcaps and not always deleting them.
=> Ensure that duplicate wallcap children aren't spawned from airlocks

Assets/Scenes/MainScene.unity
Spotted that my Drawing feature branch had not saved the wallcap removals after merging with @TimFinucane 's fix. Committing separately to be sure we have a clean master branch.
=> Fix uncommited wallcap removals after merge

.github/ISSUE_TEMPLATE/task.md
Fixes literally 2 words I missed in my Documents PR.
=> Fix new task issue template

CONTRIBUTING.md, README.md
Small grammar and other changes to README.md and CONTRIBUTING.md
=> Small document updates

Assets/Engine/Inventory/Extensions/Hands.cs
Syncs remote player's selected hand
Closes #185
=> Add selected hand change command

Assets/Content/Furniture/Storage/LockerController.controller, Assets/Content/Furniture/Storage/LockerController.controller.meta, Assets/Content/Furniture/Storage/LockerSwing.anim, Assets/Content/Furniture/Storage/LockerSwing.anim.meta, Assets/Content/Furniture/Storage/locker.prefab, Assets/Content/Scenes/MainScene.unity, Assets/Content/Systems/Interactions/Openable.cs
Adds the ability to open and close lockers with an animation.
Closes #161 
Uses the Opener script together with a new Animation Controller.
Due to interaction priorities, clicking an open locker will close it, instead of opening it's inventory.
=> Locker open/close

Assets/Content/Items/Functional/Tools/Generic/Flashlight.cs
The flashlight before was an continuous interaction, which doesn't really make sense, now it's a Toggle, interact to turn on, interact again to turn off
=> Flashlight is now a Toggle

Assets/Content/Systems/Managers/RoundManager.prefab
Reduces the round manager size as proposed by #261
=> Reduces round timer

Assets/Content/Systems/Managers/RoundManager.prefab
Extends round time to 10 minutes.
Fixes #273
=> Extend round time

ProjectSettings/QualitySettings.asset
Restores project shadow settings to the previous working version.
=> Fix shadows

Assets/Engine/Tile/TileManager.cs
Chunks tiles into batches, sending them using multiple packets
Fixes #314 
Closes #317
=> Chunk tiles to prevent packet overflow

ProjectSettings/ProjectSettings.asset
Allows you to resize and maximize the window of the build. This was bugging me.
=> Make build window resizable

Assets/Art/Animations/Creatures/Player Races/Human/Gun.meta, Assets/Content/Main Camera.prefab, Assets/Content/Structures/Wall Mounts/Light Tube Fixture.prefab, Assets/Content/World/PostProcessing/MKI.asset
Some tweaks to lights and color tones processing based on our recent feedback.
Old (current master):
New (this PR):
=> Lights and tones

Assets/Art/Models/Furniture/Machines/Atmospherics.meta, Assets/Content/Items/Cosmetic/ash.prefab.meta, Assets/Content/Scenes/MainScene.unity
- Fixes merge conflict on main scene and 2 .meta files
=> Merge conflicts from last scene update

Assets/Content/Graphics/UI/Interaction/RadialMenuUI/Classic/PetalPrefab.prefab, Assets/Content/Graphics/UI/Interaction/RadialMenuUI/RadialMenuAnimation/ContextMenu.controller, Assets/Content/Graphics/UI/Interaction/RadialMenuUI/RadialMenuAnimation/ContextPetal.controller, Assets/Engine/Interactions/UI/RadialInteractionMenuUI.cs, Assets/Engine/Interactions/UI/RadialMenuInteraction/Petal.cs, Assets/Engine/Interactions/UI/RadialMenuInteraction/RadialMenuButton.cs
Now you don't have to hover over a button to select it's interaction, just move on it's angle
Cancelling the interaction sometimes don't work
=> Changes radial selection from button to angles

Assets/Content/Furniture/Machines/Generic/Console - Surgery.prefab, Assets/Content/World/Palette05 Emission.mat, Assets/Engine/FOV/FogMaterial.mat
this fixes the FOV color and the emission material going throught it. and a little fix on the console.
=> Fixes on FOV

Assets/Engine/Atmospherics/AtmosHelper.cs, Assets/Engine/Atmospherics/AtmosHelper.cs.meta, Assets/Engine/Atmospherics/AtmosManager.cs, Assets/Engine/Atmospherics/AtmosObject.cs, Assets/Scripts.meta
Adds a few simple optimizations to the current atmos code. Improves performance from 2-4ms per frame to sub 1ms in most cases. Also gets rid of the 280kb GC allocation every frame.
Please test this thoroughly. I hope I haven't affected functionality but I can't be sure.
=> Simple atmos performance improvements

Assets/Content/Furniture/Machines/Kitchen/microwave.prefab
Fixes the missing prefab on the microwave script.
Fixes #371
=> Fix microwave destroyed item prefab

Assets/Content/Structures/Walls/BasicWall.prefab, Assets/Engine/Tile/Connections/AdvancedAdjacencyConnector.cs
Resolves an issue with View Obstacle initialization. Fixes #386
=> Fix viewobstacles

Assets/Content/Systems/Interactions/OpenInteraction.cs, Assets/Content/Systems/Managers/RoundManager.prefab, Assets/Engine/Inventory/Extensions/PickupInteraction.cs
Fixes all warning messages when starting the game.
Let me know if I missed one.
Because the network manager is on the main canvas (wtf), the main scene was modified.
Maybe it would be smart to make that a prefab?
Console warnings are annoying.
... the warning messages
=> Fix warning messages

Assets/Content/Systems/Interactions/OpenInteraction.cs, Assets/Content/Systems/Managers/RoundManager.prefab, Assets/Engine/Interactions/InteractionHandler.cs, Assets/Engine/Inventory/Extensions/PickupInteraction.cs
Changes the raycast for interactions to ignore triggers.
Closes #351
=> Interaction raycast ignores triggers

Assets/Content/Structures/Floors/Bar Floor/BarFloor.prefab, Assets/Content/Structures/Floors/FloorMesh.prefab, Assets/Content/Structures/Floors/Grey Floor/GreyFloor.prefab, Assets/Content/Structures/Floors/Kitchen Floor/KitchenFloor.prefab, Assets/Content/Structures/Floors/Plating/FloorPlating.prefab, Assets/Content/Structures/Floors/Reinforced Floor/ReinforcedFloor.prefab, Assets/Content/Structures/Floors/White Floor/WhiteFloor.prefab, Assets/Content/Structures/Floors/Wood Floor/WoodFloor.prefab
Fixes the floor collider issue caused by PR #404
=> Floor collision fix

Assets/Content/Furniture/Generic/Jukebox.prefab, Assets/Content/Items/Functional/Generic/Boombox.cs, Assets/Content/Items/Functional/Generic/boombox.prefab, Assets/Content/Items/Functional/Tools/Generic/Welder.cs, Assets/Content/Items/Weapons/Melee/Sharp/Energy Sword/EnergySword.cs, Assets/Content/Systems/Interactions/ToggleInteraction.cs
Jukebox plays sound.
Resolves #344
=> Add jukebox functionality

Assets/Content/Graphics/UI/Main Canvas.prefab, Assets/Content/Graphics/UI/Main Canvas.prefab.meta
Turns the main UI into a prefab to separate it from the scene.
=> Make MainCanvas a prefab

Assets/Content/Creatures/Human/Human.prefab, Assets/Content/Creatures/Human/HumanRagdoll.cs, Assets/Engine/Atmospherics/AtmosManager.cs, Assets/Engine/Atmospherics/AtmosRagdoll.cs, Assets/Engine/Atmospherics/AtmosRagdoll.cs.meta
Implements atmos ragdoll at high pressure differences.
Closes #432
=> Atmos ragdoll

Assets/Content/Creatures/Human/Human.mat
Updates the skin material to be more consistent with the blend file.
Old / New
=> Update skin material

Assets/Content/Items/Functional/Tools/Generic/wrench.prefab
Title.
Obstacle Mask was not properly set on the wrench prefab.
Fixes #366
=> Fix building tables inside the player

Assets/Content/Furniture/Machines/Science/Cell Charger.prefab, Assets/Content/Furniture/Machines/Science/CellCharger.cs, Assets/Engine/Inventory/Extensions/VisualContainer.cs, Assets/Engine/Inventory/Inventory.cs
Fixes the broken container on the cell charger. Also removes the callback addition in the update method, which would cause it to be called the number of frames since game start.
John should check his pr's.
Fixes #465
Closes #466
=> Fix cell charger

.github/workflows/main.yml
=> Remove buildTarget argument

Assets/Engine/Inventory/Filters/Filter.cs
Serializes the hash field on filter, making hand slots work correctly in build
=> Fix broken interactions in build

Assets/Content/Structures/Walls/BasicWall.prefab, Assets/Content/Structures/Walls/GlassWall.prefab, Assets/Content/Structures/Walls/ReinforcedGlassWall.prefab, Assets/Content/Structures/Walls/ReinforcedWall.prefab
Makes the new wall rigidbodies kinematic (unable to be moved), thus saving us from thousands of physics calculations per frame.
=> Fix wall rigidbodgies

Assets/Content/Structures/Floors/Bar Floor/BarFloor.prefab, Assets/Content/Structures/Floors/Dark Grey Floor/DarkGreyFloor.prefab, Assets/Content/Structures/Floors/Grey Floor/GreyFloor.prefab, Assets/Content/Structures/Floors/Kitchen Floor/KitchenFloor.prefab, Assets/Content/Structures/Floors/Plating/FloorPlating.prefab, Assets/Content/Structures/Floors/Reinforced Floor/ReinforcedFloor.prefab, Assets/Content/Structures/Floors/White Floor/WhiteFloor.prefab, Assets/Content/Structures/Floors/Wood Floor/WoodFloor.prefab
Replaced mesh colliders with box colliders.
Removed network identity.
=> Improve floor prefabs

Assets/Content/Creatures/Human/Human.prefab, Assets/Content/Systems/Player/PlayerListener.cs, Assets/Content/Systems/Player/PlayerListener.cs.meta
I am doubting my hearing, so make sure you check that it sounds right.
Rotates the audio listener to always be relative to the camera.
Also gets rid of unwanted audio listeners on the server or duplicate listeners on clients.
=> Make noises relative to camera orientation

Assets/Engine/Inventory/Item.cs
Makes all item animators behave normally when picked up.
Fixes #484
=> Keep animator state on disable

Assets/Engine/FOV/FieldOfView.cs
Quick hack that fixes FOV problems. Someone do this better later.
=> Make fov local

Assets/Content/Furniture/Machines/Medical/Sleeper Bed.prefab, Assets/Content/Furniture/Machines/Medical/cryotube.prefab, Assets/Content/Items/Functional/Containers/Liquid/Small Beaker.prefab, Assets/Content/Items/Functional/Containers/Liquid/beaker.prefab, Assets/Content/Items/Functional/Containers/Liquid/large beaker.prefab, Assets/Content/World/Palette05 Glass Opaque.mat, Assets/Content/World/Palette05 Glass Very Opaque.mat, Assets/Content/World/Palette05 Glass.mat
- Changes the settings on the glass materials slightly. "Glass Opaque" is now slightly less opaque and colorful. "Glass Very Opaque" is now slightly more opaque and colorful.
- Changed the cryotube and sleeper to use the very opaque.
- Changed the beakers to use opaque and removed shadows.
**Opaque Glass**
BEFORE:
AFTER:
**Very Opaque Glass**
BEFORE:
AFTER:
=> Glass Materials Update

Assets/Content/Furniture/Machines/Atmospherics/Disposal Bin/Disposal Bin.prefab, Assets/Engine/Inventory/Container.cs
Removes the issue where items appear on the ground despite being moved to container via UI.
Additionally, six slots added to Disposal Bin (previously zero).
Disposal Bin now visually appears to function correctly; however, when disposing contents the Container.cs script does give console warnings about "Trying to use a container without a filter" as well as a console error "NullReferenenceException" within the Purge() method.
Closes #515 
Closes #473 (just a different symptom of the same issue)
Closes #485 (just a different symptom of the same issue)
Closes #538
=> Resolve minor inventory and disposal bin issues

CONTRIBUTING.md
The previous link goes to the Portuguese website. I think most contributors will probably speak English. Now the link goes to the English site. Making the contribution process hassle-free is probably good.
=> Changed "contributing.md" unity link.

Assets/Engine/Inventory/Extensions/Hands.cs, Assets/Engine/Inventory/Inventory.cs, Assets/Engine/Inventory/UI/SingleItemContainerSlot.cs
Swap active hands by clicking on the hands UI. Clicking on the already active hands doesn't change the active hand. 
https://user-images.githubusercontent.com/14344825/120888145-0cf66380-c5f7-11eb-9c8b-66c8098a2a26.mp4
Closes #659
=> Add Swapping Hands with Mouse #659

.github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Config.yml, .github/ISSUE_TEMPLATE/Feature.md, Documents/CONTRIBUTING.md
- Fixed the bug and feature issues not auto-adding the labels.
- Made the description for the discussions link less wordy.
- Added info about naming to the contribution file.
=> Document Details

README.md
Content disclaimer by the download links on the readme, as requested by John.
=> Download Disclaimer

Assets/Engine/Server/Mirror/SceneLoaderManager.cs, Assets/Engine/Server/Round/RoundManager.cs
Resolves a couple of minor bugs within the Login system.
These bugs generally relate to clients performing actions that should only be performed by the server. Specific detail on changes to LoadMapList(), StartWarmup() and StartRound() methods is in the commit history.
Errors and warnings resolved:
LoginNetworkManager and RoundManager were amended.
=> Minor login system bugfixes

Assets/Content/Scenes/ServerLobby.unity, Assets/Engine/Chat/ChatWindow.cs, Assets/Engine/Chat/ToggleChat.cs, ProjectSettings/InputManager.asset
Adds the ability to press "T" to open and focus chat.
If chat is hidden, it unhides chat and focuses on the input textbox.
Added a new public method (ChatWindow.FocusInputField) that does what it says on the tin.
Added some extra code to handle the keypress and unhiding+focusing logic inside ToggleChat.Update.
Added the key to the keybindings window as well.
Might also be an idea to add a config option for re-hiding the chat window once the user has finished typing in it.
Closes #781
=> Add pressing "T" to open and focus chat

Assets/Content/Entities/Humanoids/Human/Human.prefab, Assets/Content/Furniture/Machines/Science/CellCharger.prefab, Assets/Content/Systems/Interactions/TakeInteraction.cs, Assets/Engine/Inventory/ContainerDescriptor.cs, Assets/Engine/Inventory/ContainerItemDisplay.cs, Assets/Engine/Inventory/Editor/ContainerDescriptorEditor.cs
this PR adds a few missing features to the container rework.
- Tooltips now shows on container parameters in the ContainerDescriptor.
- The take interaction changes from "first in first out" to "first in last out".
- Integrate container item display to the list of scripts handled by container descriptor.
=> Completing container rework [ready for review]

Assets/Content/Scenes/ServerLobby.unity
Fix lobby character model twitching by removing ragdoll related components.
=> Fix lobby twitching

Assets/Art/Editor/Pallete01.colors, Assets/Content/Prefabs/UI/Intro Canvas.prefab, Assets/Content/Prefabs/UI/Server Connection Screen Canvas.prefab, Assets/Scenes/Startup.unity, Assets/Scripts/External/Discord/Plugins/DiscordGameSDK/Core.cs, Assets/Scripts/External/Discord/Plugins/DiscordGameSDK/DiscordManager.cs, Assets/Scripts/External/Discord/Plugins/DiscordGameSDK/Ultimate Discord SDK.asmdef, Assets/Scripts/SS3D/Core/ApplicationStateManager.cs, Assets/Scripts/SS3D/Core/Helper/Intro/IntroUIHelper.cs, Assets/Scripts/SS3D/Core/Networking/Helper/SessionNetworkHelper.cs, Assets/Scripts/SS3D/Core/Networking/Utils/CommandLineArgs.cs
Fixes the connection screen not appearing for clients, and added a way to disable Discord integration for users that don't use it.
Added a new supported command line argument: 
- **-disablediscordintegration**
The game still crashes if you forget to disable the Discord integration and has it closed or doesn't have it installed. I created an [issue in the Discord integration GitHub page](https://github.com/eslam980/Ultimate-Discord-SDK/issues/3).
No connected issues
=> Fix connection screen and Discord integration
